.PHONY: clean All

All:
	@echo "----------Building project:[ t4 - Release ]----------"
	@cd "t4" && "$(MAKE)" -f  "t4.mk" PreBuild && "$(MAKE)" -f  "t4.mk" && "$(MAKE)" -f  "t4.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ t4 - Release ]----------"
	@cd "t4" && "$(MAKE)" -f  "t4.mk" clean
