.PHONY: clean All

All:
	@echo "----------Building project:[ ssgui - Release ]----------"
	@cd "ssgui" && "$(MAKE)" -f  "ssgui.mk" PrePreBuild && "$(MAKE)" -f  "ssgui.mk"
clean:
	@echo "----------Cleaning project:[ ssgui - Release ]----------"
	@cd "ssgui" && "$(MAKE)" -f  "ssgui.mk" clean
