.PHONY: clean All

All:
	@echo "----------Building project:[ Projekt1 - Debug ]----------"
	@cd "Projekt1" && "$(MAKE)" -f  "Projekt1.mk"
clean:
	@echo "----------Cleaning project:[ Projekt1 - Debug ]----------"
	@cd "Projekt1" && "$(MAKE)" -f  "Projekt1.mk" clean
